-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-08-15T14:02:19.054Z

CREATE TABLE "systemdata" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "datakey" varchar(64) NOT NULL,
  "value" varchar(64) NOT NULL,
  "label" varchar(64) NOT NULL,
  "sort_order" int NOT NULL DEFAULT 0,
  "is_default" boolean NOT NULL DEFAULT false
);

CREATE TABLE "plan" (
  "plan_name" varchar(64) NOT NULL,
  "code" varchar(24) UNIQUE PRIMARY KEY NOT NULL,
  "plan_cost" decimal(10,2) NOT NULL,
  "sort_order" int DEFAULT 0,
  "plan_description" varchar(512),
  "plan_details" jsonb,
  "is_public" boolean DEFAULT true
);

CREATE TABLE "useraccount" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar(26) UNIQUE NOT NULL,
  "email_address" varchar(64) UNIQUE NOT NULL,
  "password_hash" varchar(128),
  "login_on" timestamp,
  "login_count" int NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT false,
  "plan_code" varchar(16) NOT NULL,
  "source" varchar(45) DEFAULT 'email',
  "oauth_id" varchar(128),
  "email_verified_on" timestamp,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "updated_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "userprofile" (
  "useraccount_id" bigint PRIMARY KEY NOT NULL,
  "first_name" varchar(64) NOT NULL,
  "last_name" varchar(64) NOT NULL,
  "middle_name" varchar(64),
  "title" varchar(64),
  "suffix" varchar(64),
  "company" varchar(128),
  "job_title" varchar(64),
  "web_address" varchar(128),
  "mobile_number" varchar(16),
  "mailing_address" varchar(128),
  "avatar_url" varchar(128),
  "preferences" jsonb,
  "is_default" boolean NOT NULL DEFAULT false
);

CREATE TABLE "session" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "session_token" text,
  "ip_address" inet,
  "user_agent" text,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "expires_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "emailverificationtoken" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "token" text,
  "expires_on" timestamp
);

CREATE TABLE "passwordresettoken" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "token" text,
  "expires_on" timestamp
);

CREATE TABLE "contact" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar(26) UNIQUE NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "relationship" varchar(32),
  "tags" varchar(512),
  "first_name" varchar(64) NOT NULL,
  "last_name" varchar(64) NOT NULL,
  "middle_name" varchar(64),
  "title" varchar(64),
  "suffix" varchar(64),
  "company" varchar(128),
  "job_title" varchar(64),
  "web_address" varchar(128),
  "mobile_number" varchar(16),
  "mailing_address" varchar(128),
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "updated_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "contentrequest" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar(26) UNIQUE NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "contact_id" bigint NOT NULL,
  "content_type" varchar(32),
  "content_code" varchar(26) NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "viewed_on" timestamp
);

CREATE TABLE "contactevent" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "contact_id" bigint NOT NULL,
  "contentrequest_id" bigint NOT NULL,
  "event_name" varchar(16) NOT NULL,
  "event_type" varchar(16) NOT NULL,
  "event_value" varchar(32),
  "event_action" varchar(32) NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "bizcardtemplate" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "bizcard_name" varchar(64) NOT NULL,
  "bizcard_description" varchar(256),
  "bizcard_data" jsonb NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "updated_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "bizcard" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "code" varchar(26) UNIQUE NOT NULL,
  "bizcard_name" varchar(64) NOT NULL,
  "bizcard_description" varchar(128),
  "bizcard_data" jsonb,
  "bizcard_links" jsonb,
  "is_default" boolean DEFAULT false,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "updated_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "useraccount_bizcard" (
  "bizcard_id" bigint NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "created_on" timestamp DEFAULT (NOW()),
  PRIMARY KEY ("bizcard_id", "useraccount_id")
);

CREATE TABLE "qrcodetemplate" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "qrcode_name" varchar(64) NOT NULL,
  "qrcode_description" varchar(256),
  "qrcode_data" jsonb NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "updated_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE TABLE "qrcode" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "useraccount_id" bigint NOT NULL,
  "code" varchar(26) UNIQUE NOT NULL,
  "qrcode_name" varchar(64) NOT NULL,
  "qrcode_description" varchar(128),
  "qrcode_data" jsonb NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT (NOW()),
  "updated_on" timestamp NOT NULL DEFAULT (NOW())
);

CREATE UNIQUE INDEX "uq_plan_code" ON "plan" ("code");

CREATE UNIQUE INDEX "uq_useraccount_code" ON "useraccount" ("code");

CREATE INDEX "uq_useraccount_emailaddress" ON "useraccount" ("email_address");

CREATE UNIQUE INDEX "uq_userprofile_useraccount_id" ON "userprofile" ("useraccount_id");

CREATE UNIQUE INDEX "uq_contact_code" ON "contact" ("code");

CREATE INDEX "idx_contentrequest_useraccount_id" ON "contentrequest" ("useraccount_id");

CREATE UNIQUE INDEX "uq_contentrequest_code" ON "contentrequest" ("code");

CREATE INDEX "idx_contactevent_contact_id" ON "contactevent" ("contact_id");

CREATE INDEX "idx_contactevent_contentrequest_id" ON "contactevent" ("contentrequest_id");

CREATE UNIQUE INDEX "uq_bizcard_code" ON "bizcard" ("code");

CREATE INDEX "idx_bizcard_useraccount_id" ON "bizcard" ("useraccount_id");

CREATE INDEX "idx_useraccount_bizcard__useraccount_id" ON "useraccount_bizcard" ("useraccount_id");

CREATE INDEX "idx_useraccount_bizcard__bizcard_id" ON "useraccount_bizcard" ("bizcard_id");

CREATE UNIQUE INDEX "uq_qrcode_code" ON "qrcode" ("code");

CREATE INDEX "idx_qrcode_useraccount_id" ON "qrcode" ("useraccount_id");

COMMENT ON TABLE "systemdata" IS '(settings, dropdowns, enums, selections, etc.)';

COMMENT ON TABLE "plan" IS 'These are the \"Products\" that can be purchased by the user.';

COMMENT ON TABLE "useraccount" IS 'The root account denoting a user and their access credentials.';

COMMENT ON TABLE "userprofile" IS 'A larger set of searchable user information.';

COMMENT ON TABLE "contact" IS 'Represents a person.';

COMMENT ON TABLE "contentrequest" IS 'Record of a message sent to a mobile number with a link to a bizCard - (is paired with contact on creation).';

COMMENT ON COLUMN "contentrequest"."content_code" IS 'This is created when an SF user sends a bizCard via SMS to another person.';

COMMENT ON TABLE "contactevent" IS 'Represents an event related to a contact.';

COMMENT ON TABLE "bizcardtemplate" IS 'Template data from which to quickly create bizCards.';

COMMENT ON TABLE "bizcard" IS 'A personal bizCard and the data that creates it.';

COMMENT ON TABLE "useraccount_bizcard" IS 'Records that link an account with a non-owned bizCard - (a collection of bizCards)';

COMMENT ON TABLE "qrcodetemplate" IS 'Style templates used to create QR code instances.';

COMMENT ON TABLE "qrcode" IS 'Records of created QR codes to be used in creating bizCards and landing pages.';

ALTER TABLE "userprofile" ADD CONSTRAINT "fk_userprofile__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session" ADD CONSTRAINT "fk_session_useraccount__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "emailverificationtoken" ADD CONSTRAINT "fk_emailverificationtoken_useraccount__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "passwordresettoken" ADD CONSTRAINT "fk_passwordresettoken_useraccount__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contact" ADD CONSTRAINT "fk_contact__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contentrequest" ADD CONSTRAINT "fk_contentrequest__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contentrequest" ADD CONSTRAINT "fk_contentrequest__contact_id" FOREIGN KEY ("contact_id") REFERENCES "contact" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contactevent" ADD CONSTRAINT "fk_contactevent__contact_id" FOREIGN KEY ("contact_id") REFERENCES "contact" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contactevent" ADD CONSTRAINT "fk_contactevent__contentrequest_id" FOREIGN KEY ("contentrequest_id") REFERENCES "contentrequest" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bizcard" ADD CONSTRAINT "fk_bizcard__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "useraccount_bizcard" ADD CONSTRAINT "fk_useraccount_bizcard__bizcard_id" FOREIGN KEY ("bizcard_id") REFERENCES "bizcard" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "useraccount_bizcard" ADD CONSTRAINT "fk_useraccount_bizcard__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "qrcode" ADD CONSTRAINT "fk_qrcode__useraccount_id" FOREIGN KEY ("useraccount_id") REFERENCES "useraccount" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
