
# @name Get Email Verification Tokens by ID
GET {{apiRoot}}/emailverificationtokens/1
content-type: application/json

###

# @name Get Email Verification Tokens by ID
POST {{apiRoot}}/emailverificationtokens
content-type: application/json

{
  "useraccount_id": 1,
  "token": "asdfghjkl1234",
  "expires_on": "2026-12-31T23:59:59Z"
}

###

# @name Get Email Verification Token by Token
GET {{apiRoot}}/emailverificationtoken/asdfghjkl1234
content-type: application/json

### 
